USE DALISA
GO

CREATE OR ALTER PROCEDURE SP_INGRESAR(@USE VARCHAR(15),@PASS VARCHAR(15))
AS
BEGIN
SELECT * FROM TBLUSUARIO  AS U 
LEFT join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
WHERE (U.[USE] =@USE AND U.[PASS]=@PASS) AND (U.ELIMINADO=0)
END
GO

CREATE OR ALTER PROCEDURE SP_CONSULTAR_USUARIO_CORREO(@CORREO VARCHAR(40))
AS
BEGIN 
SELECT [USE],PASS FROM TBLUSUARIO AS U  WHERE  (U.ELIMINADO=0 and U.[CORREO USE] =@CORREO); 
END
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_PASSWORD_USUARIO(@PASS VARCHAR(15),@COD VARCHAR(15))
AS
BEGIN 
BEGIN TRY  
  UPDATE TBLUSUARIO
  SET PASS=@PASS
  WHERE ([ID USUARIO]= @COD  AND ELIMINADO=0);
  SELECT 1;
END TRY  
BEGIN  CATCH  
   SELECT 0;
END CATCH  
END
GO
 
CREATE OR ALTER PROCEDURE SP_CONSULTAR_USUARIO(@COD VARCHAR(10),@OPC CHAR(1))
AS
BEGIN
IF @OPC = 'S'
SELECT * FROM TBLUSUARIO  AS U 
LEFT join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
join TBLSOCIO AS S ON S.[ID USUARIO] = U.[ID USUARIO]
WHERE U.[ID USUARIO]= @COD AND (U.ELIMINADO=0)
ELSE IF @OPC = 'E'
SELECT * FROM TBLUSUARIO  AS U 
LEFT join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
join TBLEMPLEADO AS E ON E.[ID USUARIO] = U.[ID USUARIO]
WHERE U.[ID USUARIO]= @COD AND (U.ELIMINADO=0)
ELSE IF @OPC='U'
SELECT * FROM TBLUSUARIO  AS U 
LEFT join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
WHERE U.[ID USUARIO]= @COD AND (U.ELIMINADO=0)
ELSE  IF @OPC = 'D'
SELECT * FROM TBLUSUARIO  AS U 
LEFT join TBLBANCO AS B ON B.[ID BANCO] = U.[ID BANCO]
join TBLSOCIO AS S ON S.[ID USUARIO] = U.[ID USUARIO]
WHERE U.[DNI USE]= @COD AND (U.ELIMINADO=0)
END
go
CREATE or ALTER PROCEDURE SP_LISTAR_MOVIMIENTO
AS
BEGIN
select M.[ID MOVIMIENTO],US.[NOMBRE USE],U.[NOMBRE USE],M.[MONTO TRANFERENCIA],M.[FECHA MOVIMIENTO],M.[DESCRIPCION MOVI],
M.ESTADO from TBLMOVIMIENTO_SOCIO AS M join TBLUSUARIO as U on M.[ID SOCIO RECIBE] = U.[ID USUARIO] 
join TBLUSUARIO as US on M.[ID SOCIO ENVIO] = US.[ID USUARIO]
where U.ELIMINADO  in(0) ;
END
go
CREATE OR ALTER PROCEDURE SP_TRANFERIR_MOVIENTO_SOCIO(@idenvio varchar(10), @idrecibe varchar(10),@monto DECIMAL(6,3),@descripcion varchar(100))
   as
   begin
 update TBLSOCIO
set [PUNTO BONO] = ([PUNTO BONO]-(@MONTO+1))
where [ID SOCIO H]=@idenvio
update TBLSOCIO
set [PUNTO BONO] = [PUNTO BONO]+@MONTO
where [ID SOCIO H]=@idrecibe
   INSERT TBLMOVIMIENTO_SOCIO values(@idenvio,@idrecibe,@monto,GETDATE(),@descripcion,'TRANFERIDO');
   end
   go

CREATE OR ALTER PROCEDURE SP_NEXT_CODIGO(@OPC CHAR(2))
AS
BEGIN
IF @OPC = 'P'
 select 'P' +replicate ('0',(4 - len(COUNT([ID PRODUCTO])+1))) + convert(varchar, COUNT([ID PRODUCTO])+1) from TBLPRODUCTO
 ELSE IF @OPC = 'S' OR @OPC = 'E' OR @OPC='R'
 select RTRIM (@OPC)+replicate ('0',(4 - len(COUNT([ID USUARIO])+1))) + convert(varchar, COUNT([ID USUARIO])+1) from TBLUSUARIO WHERE [ID USUARIO] LIKE RTRIM (@OPC)+'%';
 ELSE IF @OPC = 'B'
 select 'Nº' +replicate ('0',(4 - len(COUNT([NUM_BOLETA])+1))) + convert(varchar, COUNT([NUM_BOLETA])+1) from TBLCABECERA_BOLETA;
END 
GO

CREATE  OR ALTER  PROCEDURE SP_CabeceraBoleta (@numeBoleta varchar(10),@idsocio varchar(10)
,@idrepar varchar(10),@fecha varchar(15),@totaPunto int ,@impt decimal(6,2),@estado varchar(50))
AS
begin
if(select count(*) from TBLCABECERA_BOLETA where NUM_BOLETA=@numeBoleta) =0
begin
if @fecha != 'null' 
insert TBLCABECERA_BOLETA values(@numeBoleta,@idsocio,@idrepar,@totaPunto,GETDATE(),@fecha,@impt,@estado);
else
insert TBLCABECERA_BOLETA values(@numeBoleta,@idsocio,@idrepar,@totaPunto,GETDATE(),null,@impt,@estado);
end
else
update TBLCABECERA_BOLETA set ESTADO=@estado where NUM_BOLETA = @numeBoleta;
end
go
DELETE FROM TBLCABECERA_BOLETA WHERE NUM_BOLETA='Nº0001'
EXEC SP_CabeceraBoleta 'Nº0002','S0003','R0001','null',1,205,'PENDIENTE'
go
create or alter procedure SP_DetalleBoleta (@nBoleta varchar(10),@idProducto varchar(10),@precio decimal(6,2),@dec DECIMAL(6,2),
@cant int,@punt int,@igv decimal (6,2),@impt  DECIMAL(6,2))
as
begin
insert TBLDETALLE_BOLETA values(@nBoleta,@idProducto,@precio,@dec,@cant,@punt,@igv,@impt)
end
go

create or alter procedure listarCabecera (@id varchar(10),@opc varchar(2))
as
begin
if @opc = 'S'
SELECT NUM_BOLETA,u.[NOMBRE USE], [TOTAL PUNTO],[FECHA PEDIDO],FECHA_ENTREGA,IMPORTTOTAL,cb.ESTADO FROM TBLCABECERA_BOLETA  AS CB
JOIN TBLREPARTIDOR AS R ON R.[ID REPARTIDOR] = CB.ID_REPARTIDOR 
JOIN TBLEMPLEADO AS e ON e.[ID EMPLEADO] =r.[ID EMPLEADO]
JOIN TBLUSUARIO AS U ON U.[ID USUARIO] =e.[ID USUARIO]
where CB.[ID SOCIO] = @id
else
SELECT NUM_BOLETA,u.[NOMBRE USE], [TOTAL PUNTO],[FECHA PEDIDO],FECHA_ENTREGA,IMPORTTOTAL,cb.ESTADO FROM TBLCABECERA_BOLETA  AS CB
JOIN TBLREPARTIDOR AS R ON R.[ID REPARTIDOR] = CB.ID_REPARTIDOR 
JOIN TBLEMPLEADO AS e ON e.[ID EMPLEADO] =r.[ID EMPLEADO]
JOIN TBLUSUARIO AS U ON U.[ID USUARIO] =e.[ID USUARIO]
end


drop trigger ACTUALIZAR_SOCIO_UPDATE


-- ------------------------------------
CREATE OR ALTER TRIGGER ACTUALIZAR_SOCIO_UPDATE
ON TBLCABECERA_BOLETA AFTER UPDATE
AS
BEGIN

if (select [ESTADO] from inserted) = 'FACTURADO'
begin
DECLARE @IDSOCIO_HIJO VARCHAR(10),@IDSOCIO_PADRE VARCHAR(10),@PUNTO INT,@CANT INT,@nBoleta varchar(10);
SELECT @IDSOCIO_HIJO= [ID SOCIO],@PUNTO = [TOTAL PUNTO],@nBoleta=NUM_BOLETA FROM INSERTED;
SELECT @CANT=SUM(CANTIDAD) FROM TBLDETALLE_BOLETA WHERE NUM_BOLETA =@nBoleta;
SELECT @IDSOCIO_PADRE=[ID SOCIO P] FROM  TBLSOCIO WHERE [ID SOCIO H] = @IDSOCIO_HIJO; 
UPDATE TBLSOCIO SET [PUNTO TOTAL PROD] =([PUNTO TOTAL PROD]+@PUNTO) WHERE [ID SOCIO H] = @IDSOCIO_HIJO;
UPDATE TBLSOCIO SET [PUNTO BONO]=([PUNTO BONO]+(select   CASE @CANT
                                 WHEN 2 THEN 38.00
								 WHEN 4 THEN 72.00
						    	 WHEN 8 THEN 144.00
	        					 WHEN 20 THEN 360.00
								 ELSE (4.00 * @CANT) END))
WHERE  [ID SOCIO H] = @IDSOCIO_PADRE; 
end
END
GO

drop trigger ACTIVACION_SOCIO

CREATE OR ALTER TRIGGER ACTIVACION_SOCIO
ON TBLSOCIO  AFTER UPDATE
AS 
BEGIN 
IF UPDATE([PUNTO TOTAL PROD])
BEGIN
UPDATE TBLSOCIO SET ACTIVADO = '1' WHERE [PUNTO TOTAL PROD]>=120 AND  [ID SOCIO H] = (SELECT [ID SOCIO H] FROM inserted);
END
END

SET DATEFORMAT  ymd

EXECUTE SP_RealizarPagoPedido 'PD0002'

EXECUTE SP_NEXT_CODIGO 'p'
update TBLSOCIO set[PUNTO BONO] =7 where [ID SOCIO H] =S0002
EXECUTE  SP_INGRESAR 'LIDIA','14124584'
EXECUTE  SP_INGRESAR 'SAM29','SAM'
EXECUTE SP_CONSULTAR_USUARIO 'S0002','S'
EXECUTE SP_CONSULTAR_USUARIO '73062100','D'
EXECUTE SP_CONSULTAR_USUARIO_CORREO 'i201922732@cibertec.edu.pe'
EXECUTE SP_UPDATE_PASSWORD_USUARIO 'SANDRA','S0001';
EXECUTE SP_AGREGAR_AFILIADO 'S0005','PERU','LIDIA PRIMITIVA','OSCCO ANCANA','1999-11-05',
'CASADO','F','14124584','MZ F15 CRUZ DE MOTUPE','LIMA','LIMA','SAN JUAN DE LURIGANCHO','989490485',
'socio5@cibertec.edu.pe','LIDIA','14124584','14547485422514',101,'PAQUETE BASICO 205','S0002';
