CREATE DATABASE DALISA;

USE DALISA;

CREATE TABLE TBLBANCO(
[ID BANCO] INT PRIMARY KEY IDENTITY(100,1) NOT NULL,
[NOMBRE BNC] VARCHAR(25) NOT NULL,
[TIPO AHORRO] VARCHAR(30) NOT NULL,
[ELIMINADO] CHAR(1) DEFAULT 0,
);

CREATE TABLE TBLUSUARIO(
[ID USUARIO] VARCHAR(10)  CHECK([ID USUARIO] LIKE '[A-Z][0-9][0-9][0-9][0-9]') PRIMARY KEY NOT NULL,
[PAIS] VARCHAR(25)  NULL ,
[NOMBRE USE] VARCHAR(35) NOT  NULL,
[APELLIDO USE] VARCHAR(35) NOT  NULL,
[FECHA NACI] DATE  NULL ,
[ESTADO CIVIL] VARCHAR(40)  NULL ,
[SEXO] CHAR(1)  NULL CHECK([SEXO] IN('M','F','O')),
[DNI USE] CHAR(8) NOT NULL UNIQUE,
[DIRECCION] VARCHAR(105)  NULL ,
[DEPARTAMENTO] VARCHAR(50)  NULL ,
[PROVINCIA] VARCHAR(50)  NULL ,
[DISTRITO] VARCHAR(50)  NULL ,
[CELULAR USE] CHAR(9)  NULL ,
[CORREO USE] VARCHAR(40) CHECK([CORREO USE] LIKE'%@%') UNIQUE NOT NULL,
[USE] VARCHAR(15) NOT NULL,
[PASS] VARCHAR(15) NOT NULL,
[CNT DEPOSITO] VARCHAR(20) NULL,
[ID BANCO] INT  NULL,
[FOTO USE] VARCHAR(100)  NULL,
[FECHA REGISTRO] DATE DEFAULT GETDATE(),
[ELIMINADO] CHAR(1) DEFAULT 0,
FOREIGN KEY([ID BANCO]) REFERENCES TBLBANCO([ID BANCO])
);

CREATE TABLE TBLSOCIO(
[ID SOCIO H] VARCHAR(10)CHECK([ID SOCIO H] LIKE '[S][0-9][0-9][0-9][0-9]') PRIMARY KEY NOT NULL,
[PUNTO BONO] DECIMAL(6,3) default 0,
[ACTIVADO] CHAR(1) NOT NULL,
[RANGO] VARCHAR(40) DEFAULT 'NIGUNO',
[PAQUETE INSCRIPTO] VARCHAR(25)  NULL,
[ID USUARIO] VARCHAR(10) UNIQUE NOT NULL,
[ID SOCIO P] VARCHAR(10) NOT NULL,
[PUNTO TOTAL PROD] INT DEFAULT 0,
[ELIMINADO] CHAR(1) DEFAULT 0,
FOREIGN KEY([ID USUARIO]) REFERENCES TBLUSUARIO([ID USUARIO])
);
CREATE TABLE TBLEMPLEADO(
	[ID EMPLEADO] VARCHAR(10) CHECK([ID EMPLEADO] LIKE '[E-R][0-9][0-9][0-9][0-9]') PRIMARY KEY NOT NULL,
	[AREA] VARCHAR(20) NOT NULL,
	[SUELDO] DECIMAL(6,3) DEFAULT 930.00,
	[ESTADO] CHAR(1) default 0,
	[ID USUARIO] VARCHAR(10) UNIQUE NOT NULL,
	[ELIMINADO] CHAR(1) DEFAULT 0,
FOREIGN KEY([ID USUARIO]) REFERENCES TBLUSUARIO([ID USUARIO])
);
CREATE TABLE TBLREPARTIDOR(
	[ID REPARTIDOR] VARCHAR(10) CHECK([ID REPARTIDOR] LIKE '[R][0-9][0-9][0-9][0-9]') PRIMARY KEY NOT NULL,
	[CANT A ENTREGA] INT NOT NULL,
	[CANT ENTREGADO] INT NOT NULL,
    [ID EMPLEADO] VARCHAR(10) NOT NULL,
FOREIGN KEY([ID EMPLEADO]) REFERENCES TBLEMPLEADO([ID EMPLEADO])
);
CREATE TABLE TBLCATEGORIA(
[ID CATEGORIA] VARCHAR(10) CHECK([ID CATEGORIA] like '[C][T][0-9][0-9][0-9][0-9]') PRIMARY  KEY NOT NULL,
[NOMBRE CATEGORIA] VARCHAR(35) NOT NULL,
[NOMBRE DESCRIPTIVO] VARCHAR(100) NOT NULL,
[ELIMINADO] CHAR(1) DEFAULT 0
);

CREATE TABLE TBLMARCA(
[ID MARCA] VARCHAR(10) CHECK([ID MARCA] like '[M][0-9][0-9][0-9][0-9]') PRIMARY  KEY NOT NULL,
[NOMBRE MARCA] VARCHAR(35) NOT NULL,
[ELIMINADO] CHAR(1) DEFAULT 0
);

CREATE TABLE TBLPRODUCTO(
[ID PRODUCTO] VARCHAR(10) CHECK([ID PRODUCTO] like '[P][0-9][0-9][0-9][0-9]') PRIMARY  KEY NOT NULL,
[NOMBRE PROD] VARCHAR(45) NOT NULL,
[DESCRIP PROD] VARCHAR(400)NOT NULL,
[ID CATEGORIA] VARCHAR(10) NOT NULL,
[ID MARCA] VARCHAR(10) NOT NULL,
[PRECIO PROD] DECIMAL(6,2) NOT NULL  CHECK([PRECIO PROD] >=0),
[CANTIDAD PROD] INT NOT NULL CHECK([CANTIDAD PROD] >=0),
[PUNTO PROD] INT NOT NULL,
[FOTO PROD] VARCHAR(100)   NULL,
[FECHA REGISTRO] DATE DEFAULT GETDATE(),
[ELIMINADO] CHAR(1) DEFAULT 0,
FOREIGN KEY ([ID CATEGORIA]) REFERENCES TBLCATEGORIA([ID CATEGORIA]),
FOREIGN KEY ([ID MARCA]) REFERENCES TBLMARCA([ID MARCA])
);


CREATE TABLE TBLCABECERA_PEDIDO(
[NUM_PEDIDO] VARCHAR(10) CHECK([NUM_PEDIDO] like '[P][D][0-9][0-9][0-9][0-9]') PRIMARY  KEY NOT NULL,
[ID SOCIO] VARCHAR(10) NOT NULL,
[ID_REPARTIDOR] VARCHAR(10) NULL,
[TOTAL PUNTO] INT NOT NULL,
[FECHA PEDIDO] DATETIME DEFAULT GETDATE(),
[FECHA_ENTREGA] DATETIME  NULL ,
[IMPORTTOTAL] DECIMAL(6,2) NOT NULL,

FOREIGN KEY ([ID SOCIO]) REFERENCES TBLSOCIO([ID SOCIO H]),
FOREIGN KEY ([ID_REPARTIDOR]) REFERENCES TBLREPARTIDOR([ID REPARTIDOR])
);drop table TBLCABECERA_BOLETA
drop table TBLDETALLE_BOLETA
CREATE TABLE TBLCABECERA_BOLETA(
[NUM_BOLETA] VARCHAR(10) CHECK([NUM_BOLETA] like '[N][º][0-9][0-9][0-9][0-9]') PRIMARY  KEY NOT NULL,
[ID SOCIO] VARCHAR(10) NOT NULL,
[ID_REPARTIDOR] VARCHAR(10) NULL,
[TOTAL PUNTO] INT NOT NULL,
[FECHA PEDIDO] DATETIME DEFAULT GETDATE(),
[FECHA_ENTREGA] DATETIME  default NULL ,
[IMPORTTOTAL] DECIMAL(6,2) NOT NULL,
[ESTADO] varchar(50) NOT NULL check([ESTADO]IN('PENDIENTE','EN CAMINO','FACTURADO','CANCELADO'))
FOREIGN KEY ([ID SOCIO]) REFERENCES TBLSOCIO([ID SOCIO H]),
FOREIGN KEY ([ID_REPARTIDOR]) REFERENCES TBLREPARTIDOR([ID REPARTIDOR])
);

CREATE TABLE TBLDETALLE_BOLETA(
[id] int IDENTITY(1,1)  primary key NOT NULL ,
[NUM_BOLETA] VARCHAR(10)  NOT NULL,
[ID PRODUCTO] VARCHAR(10) NOT NULL,
[PRECIO]DECIMAL(6,2) not null,
[DESCUENTO] DECIMAL(6,2) not null,
[CANTIDAD] INT NOT NULL,
[PUNTO] INT NOT NULL,
[IGV] DECIMAL(6,2) not null,
[IMPORTPAGAR] DECIMAL(6,2) NOT NULL,
FOREIGN KEY ([NUM_BOLETA]) REFERENCES TBLCABECERA_BOLETA([NUM_BOLETA]),
FOREIGN KEY ([ID PRODUCTO]) REFERENCES TBLPRODUCTO([ID PRODUCTO]),
);

CREATE TABLE TBLMOVIMIENTO_SOCIO(
[ID MOVIMIENTO] int primary key IDENTITY(1,1)  NOT NULL,
[ID SOCIO ENVIO]VARCHAR(10) NOT NULL,
[ID SOCIO RECIBE] VARCHAR(10) NOT NULL,
[MONTO TRANFERENCIA] DECIMAL(6,3) DEFAULT 0,
[FECHA MOVIMIENTO] DATE NOT NULL,
[DESCRIPCION MOVI] VARCHAR(100)NOT NULL,
[ESTADO]  VARCHAR(50)NOT NULL,
FOREIGN KEY ([ID SOCIO ENVIO]) REFERENCES TBLSOCIO([ID SOCIO H]),
FOREIGN KEY ([ID SOCIO RECIBE]) REFERENCES TBLSOCIO([ID SOCIO H])
);

